/** Run every test module and exit nonzero if any fail. */
import { run as runTranscript } from './transcript.test.js';
import { run as runTitleCache } from './title-cache.test.js';
import { run as runScan } from './scan.test.js';
import { run as runUsage } from './usage.test.js';
import { run as runAgents } from './agents.test.js';
import { run as runAgentsCache } from './agents-cache.test.js';
import { run as runChat } from './chat.test.js';
import { run as runAnalyze } from './analyze.test.js';
import { run as runMarkdown } from './markdown.test.js';
import { run as runChatFilter } from './chat-filter.test.js';
import { run as runFilterSort } from './filter-sort.test.js';
import { run as runAnalyticsFilterSort } from './analytics-filter-sort.test.js';
import { run as runFrontmatter } from './frontmatter.test.js';
import { run as runManagement } from './management.test.js';
import { run as runManagementEntries } from './management-entries.test.js';
import { run as runSessionAnalyticsLog } from './sessionAnalyticsLog.test.js';
import { run as runAnalytics } from './analytics.test.js';
import { run as runPending } from './pending.test.js';
import { run as runPlans } from './plans.test.js';
import { run as runMessages } from './messages.test.js';
import { run as runPermissions } from './permissions.test.js';
import { run as runRemoteState } from './remoteState.test.js';
import { run as runOrigin } from './origin.test.js';
import { run as runSettings } from './settings.test.js';
import { run as runClientSettings } from './client-settings.test.js';
import { run as runNotify } from './notify.test.js';
import { run as runDeepLink } from './deep-link.test.js';
import { run as runTranscribe } from './transcribe.test.js';

let failed = 0;
failed += runTranscript();
failed += runTitleCache();
failed += runScan();
failed += runUsage();
failed += runAgents();
failed += runAgentsCache();
failed += runChat();
failed += runAnalyze();
failed += runMarkdown();
failed += runChatFilter();
failed += runFilterSort();
failed += runAnalyticsFilterSort();
failed += runFrontmatter();
failed += await runManagement();
failed += runManagementEntries();
failed += runSessionAnalyticsLog();
failed += runAnalytics();
failed += await runPending();
failed += await runPlans();
failed += await runMessages();
failed += await runPermissions();
failed += runRemoteState();
failed += runOrigin();
failed += runSettings();
failed += runClientSettings();
failed += await runNotify();
failed += runDeepLink();
failed += await runTranscribe();

console.log(failed > 0 ? `FAILED (${failed})` : 'ALL PASS');
process.exit(failed > 0 ? 1 : 0);
