/**
 * guides.ts — pure metadata extraction for the Guides tab (GET /api/guides).
 * Reads a tutor deck's `<title>` and its `id="provenance"` JSON stamp via
 * targeted regexes, not a full HTML parser.
 *
 * Regex extraction is deliberate and safe here: every file under
 * docs/published-guides/ is machine-generated by the tutor/study skills —
 * never adversarial HTML — so there is no untrusted-input surface a real
 * parser would need to defend against.
 *
 * Everything here fails open: a missing marker, missing stamp, or malformed
 * JSON yields null fields, never a throw.
 */

import type { DeckSection } from '../../shared/types.js';

/** The tutor skill writes this literal comment right after `<!DOCTYPE html>`. */
const TUTOR_DECK_MARKER = '<!-- tutor-deck -->';

/** How far into the file isTutorDeck looks for the marker. */
const MARKER_WINDOW = 1024;

/** Suffix the tutor skill appends to every deck's `<title>`; stripped for display. */
const TUTOR_TITLE_SUFFIX = ' — a tutor lesson';

/** The provenance stamp, exactly as the tutor skill writes the opening tag. */
const PROVENANCE_RE = /<script type="application\/json" id="provenance">([\s\S]*?)<\/script>/;

const TITLE_RE = /<title>([\s\S]*?)<\/title>/;

/** True iff `html` is a tutor deck, per the marker the skill writes right after `<!DOCTYPE html>`. */
export function isTutorDeck(html: string): boolean {
  return html.slice(0, MARKER_WINDOW).includes(TUTOR_DECK_MARKER);
}

/** First `<title>` element's text, with the tutor-deck suffix stripped when present. */
export function extractTitle(html: string): string | null {
  const match = html.match(TITLE_RE);
  if (!match) return null;
  const title = match[1];
  return title.endsWith(TUTOR_TITLE_SUFFIX) ? title.slice(0, -TUTOR_TITLE_SUFFIX.length) : title;
}

/**
 * Title, generation stamp, and quiz sections for a tutor deck. Title comes
 * from extractTitle; the rest from the first `id="provenance"` JSON script
 * block. A missing stamp or a parse failure leaves generated/commit/sections
 * null while title still works — the two halves are independent.
 */
export function parseDeckMeta(html: string): {
  title: string | null;
  generated: string | null;
  commit: string | null;
  sections: DeckSection[] | null;
} {
  const title = extractTitle(html);
  const withoutStamp = { title, generated: null, commit: null, sections: null };

  const match = html.match(PROVENANCE_RE);
  if (!match) return withoutStamp;

  let stamp: any;
  try {
    stamp = JSON.parse(match[1]);
  } catch {
    return withoutStamp;
  }
  if (!stamp || typeof stamp !== 'object') return withoutStamp;

  const generated = typeof stamp.generated === 'string' ? stamp.generated : null;
  const commit = typeof stamp.commit === 'string' ? stamp.commit : null;
  const sections = Array.isArray(stamp.sections)
    ? stamp.sections
        .filter((s: any) => s && typeof s.id === 'string' && typeof s.title === 'string')
        .map((s: any) => ({ id: s.id as string, title: s.title as string }))
    : null;

  return { title, generated, commit, sections };
}
