/**
 * guides.ts — pure metadata extraction for the Guides tab (GET /api/guides),
 * plus scanGuides(), the recursive directory walk over docs/published-guides/
 * that builds the GuidesIndex the endpoint serves.
 *
 * Reads a tutor deck's `<title>` and its `id="provenance"` JSON stamp via
 * targeted regexes, not a full HTML parser.
 *
 * Regex extraction is deliberate and safe here: every file under
 * docs/published-guides/ is machine-generated by the tutor/study skills —
 * never adversarial HTML — so there is no untrusted-input surface a real
 * parser would need to defend against.
 *
 * Everything here fails open: a missing marker, missing stamp, malformed
 * JSON, or an unreadable file/directory yields null fields or an empty
 * result, never a throw.
 */

import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';

import type { DeckRef, DeckSection, GuideRef, GuidesIndex } from '../../shared/types.js';

/** The tutor skill writes this literal comment right after `<!DOCTYPE html>`. */
const TUTOR_DECK_MARKER = '<!-- tutor-deck -->';

/** How far into the file isTutorDeck looks for the marker. */
const MARKER_WINDOW = 1024;

/** Suffix the tutor skill appends to every deck's `<title>`; stripped for display. */
const TUTOR_TITLE_SUFFIX = ' — a tutor lesson';

/** The provenance stamp, exactly as the tutor skill writes the opening tag. */
const PROVENANCE_RE = /<script type="application\/json" id="provenance">([\s\S]*?)<\/script>/;

const TITLE_RE = /<title>([\s\S]*?)<\/title>/;

/** True iff `html` is a tutor deck, per the marker the skill writes right after `<!DOCTYPE html>`. */
export function isTutorDeck(html: string): boolean {
  return html.slice(0, MARKER_WINDOW).includes(TUTOR_DECK_MARKER);
}

/** First `<title>` element's text, with the tutor-deck suffix stripped when present. */
export function extractTitle(html: string): string | null {
  const match = html.match(TITLE_RE);
  if (!match) return null;
  const title = match[1];
  return title.endsWith(TUTOR_TITLE_SUFFIX) ? title.slice(0, -TUTOR_TITLE_SUFFIX.length) : title;
}

/**
 * Title, generation stamp, and quiz sections for a tutor deck. Title comes
 * from extractTitle; the rest from the first `id="provenance"` JSON script
 * block. A missing stamp or a parse failure leaves generated/commit/sections
 * null while title still works — the two halves are independent.
 */
export function parseDeckMeta(html: string): {
  title: string | null;
  generated: string | null;
  commit: string | null;
  sections: DeckSection[] | null;
} {
  const title = extractTitle(html);
  const withoutStamp = { title, generated: null, commit: null, sections: null };

  const match = html.match(PROVENANCE_RE);
  if (!match) return withoutStamp;

  let stamp: any;
  try {
    stamp = JSON.parse(match[1]);
  } catch {
    return withoutStamp;
  }
  if (!stamp || typeof stamp !== 'object') return withoutStamp;

  const generated = typeof stamp.generated === 'string' ? stamp.generated : null;
  const commit = typeof stamp.commit === 'string' ? stamp.commit : null;
  const sections = Array.isArray(stamp.sections)
    ? stamp.sections
        .filter((s: any) => s && typeof s.id === 'string' && typeof s.title === 'string')
        .map((s: any) => ({ id: s.id as string, title: s.title as string }))
    : null;

  return { title, generated, commit, sections };
}

/** Read a file's text, or null if it can't be read — never throws. */
async function readFileOrNull(p: string): Promise<string | null> {
  try {
    return await fsp.readFile(p, 'utf8');
  } catch {
    return null;
  }
}

/** generated descending, nulls last; any tie (including null-vs-null) breaks by relPath ascending. */
function compareDecks(a: DeckRef, b: DeckRef): number {
  if (a.generated !== b.generated) {
    if (a.generated === null) return 1;
    if (b.generated === null) return -1;
    return a.generated < b.generated ? 1 : -1;
  }
  return a.relPath < b.relPath ? -1 : a.relPath > b.relPath ? 1 : 0;
}

interface WalkResult {
  decks: DeckRef[];
  guides: GuideRef[];
}

const EMPTY_WALK: WalkResult = { decks: [], guides: [] };

/**
 * Recursively scan one directory for decks and guides. `relDir` is the
 * POSIX-style path from the scan root to `dir` (`''` at the root itself) —
 * built by hand with `/` throughout rather than via `path.join`, so relPath
 * never picks up a platform separator.
 *
 * Non-descent rule (deliberate, not an oversight): a directory other than
 * the root whose immediate children include `index.html` is a *guide
 * directory*. It becomes exactly one GuideRef, and its entire subtree — every
 * file and subdirectory beneath it — is skipped from here on. A guide's own
 * supporting files (a `guide/` subdir of source notes, a `tools/` subdir of
 * scripts, or even a marker'd deck the guide happens to embed) must never
 * surface as a second, nested guide or a stray deck. The check runs before
 * anything in this directory is otherwise inspected, and returns immediately
 * — nothing below this point in the function runs for a guide directory.
 */
async function scanDir(dir: string, relDir: string): Promise<WalkResult> {
  let entries: fs.Dirent[];
  try {
    entries = await fsp.readdir(dir, { withFileTypes: true });
  } catch {
    return EMPTY_WALK; // unreadable directory — fail open, skip it
  }

  const isRoot = relDir === '';

  // Guide directory: see the non-descent rule in the function doc above.
  if (!isRoot && entries.some(e => e.isFile() && e.name === 'index.html')) {
    const html = await readFileOrNull(path.join(dir, 'index.html'));
    const guide: GuideRef = {
      relPath: relDir,
      name: path.basename(dir),
      title: html === null ? null : extractTitle(html),
    };
    return { decks: [], guides: [guide] };
  }

  const results = await Promise.all(entries.map(async (entry): Promise<WalkResult> => {
    const rel = isRoot ? entry.name : `${relDir}/${entry.name}`;

    if (entry.isDirectory()) return scanDir(path.join(dir, entry.name), rel);
    if (!entry.isFile() || !entry.name.endsWith('.html')) return EMPTY_WALK;
    if (isRoot && entry.name === 'index.html') return EMPTY_WALK; // the GitHub Pages hub itself

    const html = await readFileOrNull(path.join(dir, entry.name));
    if (html === null || !isTutorDeck(html)) return EMPTY_WALK;

    const meta = parseDeckMeta(html);
    const deck: DeckRef = {
      relPath: rel,
      title: meta.title ?? entry.name.slice(0, -'.html'.length),
      generated: meta.generated,
      commit: meta.commit,
      sections: meta.sections,
    };
    return { decks: [deck], guides: [] };
  }));

  return {
    decks: results.flatMap(r => r.decks),
    guides: results.flatMap(r => r.guides),
  };
}

/**
 * Build the Guides tab's index by walking `guidesDir` (docs/published-guides/)
 * for tutor decks and study guides. Never rejects: a missing/unreadable
 * `guidesDir`, or any unreadable entry within it, is treated as simply
 * absent rather than as an error (see scanDir) — an empty tab, not a broken
 * one, and no `error` flag is set for it.
 */
export async function scanGuides(guidesDir: string): Promise<GuidesIndex> {
  let walked: WalkResult = EMPTY_WALK;
  try {
    walked = await scanDir(guidesDir, '');
  } catch {
    // Defensive only: scanDir already wraps every fallible call in its own
    // try/catch. This outer net just makes "never rejects" an absolute
    // guarantee rather than one contingent on scanDir's internals.
  }

  return {
    generatedAt: new Date().toISOString(),
    decks: [...walked.decks].sort(compareDecks),
    guides: [...walked.guides].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0)),
  };
}

/**
 * Resolve `relPath` (as requested by Task 4's `GET /guides/<relPath>`) to an
 * absolute on-disk path inside `guidesDir`, or `null` if anything about the
 * request is unsafe or the target doesn't qualify.
 *
 * This is the feature's entire security surface: docs/published-guides/
 * sits inside the repo, alongside `.env` (the ntfy push topic and the
 * remote-answer token). Every check below exists solely to keep this
 * function from ever handing back a path outside `guidesDir`.
 *
 * Checks run in this order — cheap string rejects on the raw, unresolved
 * `relPath` first; filesystem syscalls only for survivors:
 *   1. non-empty.
 *   2. no `..` path segment. This means an exact segment equal to `..`
 *      (e.g. the second segment of "a/../b") — a filename that merely
 *      *contains* ".." as a substring, like "a..b.html", is a literal,
 *      filesystem-safe name and is left alone: only an exact ".." segment
 *      means "go up a directory" to the filesystem.
 *   3. no leading "/" (would make `path.join` treat relPath as its own
 *      absolute root, ignoring `guidesDir`, on POSIX).
 *   4. no backslash (not a POSIX separator, but rejected outright rather
 *      than special-cased per platform).
 *   5. no NUL byte (Node's `fs` calls throw a TypeError on one; reject up
 *      front rather than lean on the catch-all below for this case).
 *   6. `fs.realpathSync` BOTH `guidesDir` and the joined candidate path, and
 *      require the resolved target to sit strictly inside the resolved
 *      root: `target.startsWith(root + path.sep)`.
 *
 *      Both sides must be realpath'd, not just the target. On macOS,
 *      `os.tmpdir()` — and so most tmpdir-based fixtures — already lives
 *      under a symlink (`/var` -> `/private/var`), so comparing a
 *      realpath'd target against a raw `guidesDir` string would fail this
 *      check for every request, traversal or not.
 *
 *      The separator in `root + path.sep` is deliberate, and stricter than
 *      `serveStatic`'s prefix check (server/index.ts:78), which tests
 *      `startsWith(clientDist)` with no separator — a check that a sibling
 *      directory named e.g. "guides-secret" would pass. Do not "simplify"
 *      this back to match serveStatic; the asymmetry is the point.
 *
 *      This same step also transparently rejects: a symlink (file or
 *      directory) that leads outside `guidesDir`, since realpath follows it
 *      before the prefix check runs; and a relPath that resolves to
 *      `guidesDir` itself (e.g. "."), since the exact root has no trailing
 *      separator and so never matches its own `root + sep` prefix.
 *   7. the resolved target is a regular file — not a directory, not a
 *      device, etc.
 *
 * Never throws: a nonexistent path (ENOENT from realpathSync), a broken
 * symlink, a permissions error, a bogus `guidesDir`, or any other failure
 * during resolution is caught and yielded as `null`, the same as a
 * deliberate traversal attempt.
 */
export function resolveGuidePath(guidesDir: string, relPath: string): string | null {
  if (relPath === '') return null;
  if (relPath.split('/').includes('..')) return null;
  if (relPath.startsWith('/')) return null;
  if (relPath.includes('\\')) return null;
  if (relPath.includes('\0')) return null;

  try {
    const root = fs.realpathSync(guidesDir);
    const target = fs.realpathSync(path.join(guidesDir, relPath));
    if (!target.startsWith(root + path.sep)) return null;
    if (!fs.statSync(target).isFile()) return null;
    return target;
  } catch {
    return null;
  }
}

/**
 * MIME lookup for GET /guides/<relPath> (Task 4). The first eight entries
 * mirror the private `MIME` map in server/index.ts:62-71 verbatim (same
 * keys, same values) — duplicated rather than imported, since that map is
 * module-private there. `.mjs` and `.md` are added for guide content:
 * tutor decks load ES modules directly, and study guides can serve their
 * source Markdown alongside the rendered HTML.
 *
 * Lookup (at the call site, not here) is a plain `GUIDE_MIME[ext]` keyed by
 * `path.extname(...)`, same as the map it mirrors — no case-folding, so an
 * uppercase extension misses and falls back to `application/octet-stream`,
 * exactly like the existing MIME map already behaves.
 */
export const GUIDE_MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.mjs': 'text/javascript; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8',
};
